image: python:latest

before_script:
  - git config --global user.name "Gitlab CI"
  - git config --global user.email "GitlabCI@Gitlab.ru"
  - pip install mkdocs mkdocs-material pymdown-extensions mkdocs-awesome-pages-plugin mkdocs-minify-plugin pygments-bsl mkdocs-git-revision-date-localized-plugin

variables:
  GIT_DEPTH: 1000

pages:
  stage: deploy
  script:
  - mkdocs build -s
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  stage: test
  script:
  - mkdocs build -s
  only:
  - merge_requests
